# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
 adapter: postgresql
 encoding: SQL_ASCII
 username: postgres
 password: password

development:
  <<: *default
  host: localhost
  database: sot_development

test:
  <<: *default
  host: localhost
  database: sot_test

production:
  <<: *default
  database: sot_production
